# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84f53b2753c83ada3b7d003e486cad0bbb8abc24dcbee36207c3d2d7f0780d81ee16f5ba8eb955097a553c394c619221fabe5b6c9243ca9d5d23d606d5bb231f

test:
  secret_key_base: 80f38329f5b590bee05de1c683043f9d8f2e245a099b26d1fac0a88114ec317cf2c3b233aa77f54fce1654cd7920671eca32b6054e551a02d3a5824671d0cca9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
